from __future__ import annotations

from pprint import pformat

from .model import ProjectModel


SYNAPSE_LIBRARY = {
    "AMPA": {"mod": "Exp2Syn", "tau1": 0.1, "tau2": 2.0, "e": 0.0},
    "NMDA": {"mod": "Exp2Syn", "tau1": 1.0, "tau2": 20.0, "e": 0.0},
    "GABA_A": {"mod": "Exp2Syn", "tau1": 0.5, "tau2": 8.0, "e": -75.0},
    "GABA_B": {"mod": "Exp2Syn", "tau1": 5.0, "tau2": 80.0, "e": -90.0},
}


def _sanitize(name: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in name)


def _round(value: float) -> float:
    return round(float(value), 6)


def generate_netpyne_script(project: ProjectModel) -> str:
    lines: list[str] = []
    lines.append('"""Generated by NetPyNe Modeler."""')
    lines.append("")
    lines.append("from netpyne import specs, sim")
    lines.append("")
    lines.append("netParams = specs.NetParams()")
    lines.append("simConfig = specs.SimConfig()")
    lines.append("")
    lines.append(f"# Project title: {project.metadata.title}")
    for note_line in project.metadata.description.splitlines():
        lines.append(f"# {note_line}")
    lines.append("")

    used_synapses = sorted({connection.synapse for connection in project.connections})
    lines.append("# Synaptic mechanisms")
    for synapse_name in used_synapses:
        params = SYNAPSE_LIBRARY.get(synapse_name, SYNAPSE_LIBRARY["AMPA"])
        lines.append(
            f"netParams.synMechParams['{synapse_name}'] = "
            f"{pformat(params, width=88)}"
        )
    lines.append("")

    lines.append("# Cell rules and populations")
    for population in project.populations:
        cell_type = _sanitize(population.label)
        if population.representation == "compartmental":
            cell_rule_name = f"{cell_type}_rule"
            cell_model = "HH_active"
            cell_rule = {
                "conds": {"cellType": cell_type, "cellModel": cell_model},
                "secs": {
                    "soma": {
                        "geom": {
                            "diam": _round(population.electrophysiology.soma_diam),
                            "L": _round(population.electrophysiology.soma_L),
                            "Ra": _round(population.electrophysiology.ra),
                            "cm": _round(population.electrophysiology.cm),
                        },
                        "mechs": {
                            "hh": {
                                "gnabar": _round(population.electrophysiology.gnabar_hh),
                                "gkbar": _round(population.electrophysiology.gkbar_hh),
                                "gl": _round(population.electrophysiology.gl_hh),
                                "el": _round(population.electrophysiology.el_hh),
                            }
                        },
                        "vinit": _round(population.electrophysiology.v_init),
                    }
                },
            }
            lines.append(
                f"netParams.cellParams['{cell_rule_name}'] = "
                f"{pformat(cell_rule, width=88)}"
            )
            pop_params = {
                "cellType": cell_type,
                "cellModel": cell_model,
                "numCells": int(population.size),
            }
        else:
            point_model = population.electrophysiology.point_model
            point_params = {"cellModel": point_model, "numCells": int(population.size)}
            if point_model == "IntFire2":
                point_params.update(
                    {
                        "taum": _round(population.electrophysiology.point_params["taum"]),
                        "taus": _round(population.electrophysiology.point_params["taus"]),
                        "ib": _round(population.electrophysiology.point_params["ib"]),
                    }
                )
            else:
                point_params.update(
                    {
                        "tau": _round(population.electrophysiology.point_params["tau"]),
                        "refrac": _round(population.electrophysiology.point_params["refrac"]),
                    }
                )
            point_params["cellType"] = cell_type
            pop_params = point_params

        lines.append(
            f"netParams.popParams['{population.id}'] = "
            f"{pformat(pop_params, width=88)}"
        )
        if population.notes:
            for note_line in population.notes.splitlines():
                lines.append(f"# {population.id}: {note_line}")
        lines.append("")

    lines.append("# Connectivity")
    for connection in project.connections:
        conn_name = _sanitize(connection.label) or connection.id
        conn_params = {
            "preConds": {"pop": connection.pre},
            "postConds": {"pop": connection.post},
            "synMech": connection.synapse,
            "weight": _round(connection.weight),
            "delay": _round(connection.delay),
            "probability": _round(connection.probability),
        }
        if connection.stdp.enabled:
            conn_params["plasticity"] = {
                "mech": "STDP",
                "params": {
                    "hebbwt": _round(connection.stdp.causal_gain),
                    "antiwt": -_round(abs(connection.stdp.noncausal_penalty)),
                    "wmax": _round(connection.stdp.max_weight),
                    "RLon": 0,
                    "tauhebb": _round(connection.stdp.timing_window_ms),
                },
            }
        lines.append(
            f"netParams.connParams['{conn_name}'] = "
            f"{pformat(conn_params, width=88)}"
        )
        if connection.stdp.enabled:
            lines.append(
                f"# {connection.id}: objective={connection.stdp.objective}, "
                f"scaling={connection.stdp.scaling_mode}"
            )
        if connection.notes:
            for note_line in connection.notes.splitlines():
                lines.append(f"# {connection.id}: {note_line}")
        lines.append("")

    lines.append("# Simulation defaults")
    lines.append("simConfig.duration = 1_000")
    lines.append("simConfig.dt = 0.025")
    lines.append("simConfig.verbose = False")
    lines.append("simConfig.recordTraces = {'V_soma': {'sec': 'soma', 'loc': 0.5, 'var': 'v'}}")
    lines.append("simConfig.recordStep = 0.1")
    lines.append("simConfig.analysis['plotRaster'] = {'saveFig': True}")
    lines.append("simConfig.analysis['plotTraces'] = {'include': [0], 'saveFig': True}")
    lines.append("")
    lines.append("sim.createSimulateAnalyze(netParams=netParams, simConfig=simConfig)")
    lines.append("")
    return "\n".join(lines)
